const TAUNTS = {
  correctGuess: [
    "LUCKY GUESS, {username}. IT CHANGES NOTHING.",
    "ONE LETTER WILL NOT SAVE YOUR COUNTRY, {username}.",
    "EVEN A BROKEN CLOCK IS RIGHT TWICE A DAY.",
    "YOU DELAY THE INEVITABLE.",
    "IMPRESSIVE... FOR AN AMERICAN.",
    "DO NOT CELEBRATE YET, {username}. THE CLOCK IS STILL TICKING.",
    "A SMALL VICTORY IN A WAR YOU CANNOT WIN.",
    "YOUR INTELLIGENCE AGENCIES TAUGHT YOU WELL... BUT NOT WELL ENOUGH.",
    "ENJOY THIS MOMENT. IT WILL BE YOUR LAST.",
    "SO YOU CAN SPELL. THE MOTHERLAND IS NOT IMPRESSED.",
  ],

  wrongEarly: [
    "ANOTHER FAILURE. THE COUNTDOWN CONTINUES.",
    "YOU CANNOT STOP WHAT HAS BEGUN, AMERICAN.",
    "YOUR ATTEMPTS ARE FUTILE.",
    "THE MOTHERLAND WILL PREVAIL.",
    "IS THIS THE BEST THE WEST HAS TO OFFER?",
    "EACH WRONG GUESS BRINGS THE LAUNCH CLOSER.",
    "I EXPECTED MORE FROM YOU, {username}.",
    "YOUR DEFENSES ARE AS WEAK AS YOUR GUESSES.",
    "PERHAPS YOU SHOULD TRY DIPLOMACY INSTEAD.",
  ],

  wrongMid: [
    "YOUR ATTEMPTS ARE FUTILE. THE LAUNCH CONTINUES.",
    "HALF YOUR CHANCES ARE GONE, {username}.",
    "I CAN ALMOST HEAR THE SIRENS IN WASHINGTON.",
    "YOUR PRESIDENT CANNOT HELP YOU NOW.",
    "THE SILOS ARE OPENING, {username}. TICK TOCK.",
    "YOU ARE RUNNING OUT OF TIME AND OPTIONS.",
    "MAYBE YOU SHOULD CALL YOUR FAMILY WHILE YOU STILL CAN.",
    "THE TRAJECTORY IS ALREADY CALCULATED. YOU ARE TOO SLOW.",
    "HALFWAY THERE. THE WARHEADS ARE EAGER.",
  ],

  wrongLate: [
    "IT IS ALMOST OVER. SAY GOODBYE TO YOUR CITIES.",
    "ONE MORE MISTAKE AND IT IS ALL OVER.",
    "CAN YOU HEAR THE WARHEADS WARMING UP?",
    "YOUR FAMILY... THEY LIVE IN A CITY, DA?",
    "THE END IS NEAR. I CAN TASTE THE VICTORY.",
    "YOUR HANDS ARE SHAKING, {username}. I CAN TELL.",
    "FINAL STAGE. THERE IS NO TURNING BACK NOW.",
    "THE LAUNCH CODES ARE ALMOST COMPLETE. GOODBYE, AMERICA.",
    "DO YOU HEAR THAT RUMBLING? THAT IS DESTINY.",
  ],

  gameOverLoss: [
    "GAME OVER. THE MISSILES FLY. GLORY TO THE MOTHERLAND!",
    "YOU HAVE FAILED. PREPARE FOR NUCLEAR WINTER.",
    "GOODBYE, {username}. IT WAS ALMOST FUN.",
    "THE WORLD BURNS BECAUSE OF YOUR INCOMPETENCE, {username}.",
    "LAUNCH CONFIRMED. THERE IS NOTHING LEFT TO SAY.",
    "YOU HAD YOUR CHANCE. NOW THE SKY WILL GLOW.",
  ],

  gameOverWin: [
    "IMPOSSIBLE! HOW DID YOU... THIS IS NOT OVER.",
    "YOU WIN THIS TIME, {username}. NEXT TIME YOU WILL NOT BE SO LUCKY.",
    "THE LAUNCH IS ABORTED... FOR NOW.",
    "NYET! THIS CANNOT BE! I WILL RETURN, {username}.",
    "YOU HAVE WON THE BATTLE, BUT THE WAR IS FAR FROM OVER.",
    "IMPRESSIVE, {username}. THE MOTHERLAND UNDERESTIMATED YOU.",
  ],
};

function pickRandom(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

function getTaunt(context) {
  const { username, hit, launchStage, gameOver, won } = context;
  let pool;

  if (gameOver) {
    pool = won ? TAUNTS.gameOverWin : TAUNTS.gameOverLoss;
  } else if (hit) {
    pool = TAUNTS.correctGuess;
  } else if (launchStage <= 2) {
    pool = TAUNTS.wrongEarly;
  } else if (launchStage <= 4) {
    pool = TAUNTS.wrongMid;
  } else {
    pool = TAUNTS.wrongLate;
  }

  return pickRandom(pool).replace(/\{username\}/g, username || 'AMERICAN');
}

module.exports = { getTaunt };
